import type { Partner, PartnerPayout, PartnerPerformance } from "@/types/partner"

export const mockPartners: Partner[] = [
  {
    id: "p1",
    name: "CleanPro Services",
    email: "contact@cleanpro.com",
    phone: "+91 98765 43210",
    city: "Mumbai",
    areas: ["Bandra", "Andheri", "Juhu"],
    services: ["Home Cleaning", "Deep Cleaning", "Office Cleaning"],
    joinDate: "2023-06-15",
    status: "active",
    kycStatus: "verified",
    rating: 4.8,
    totalBookings: 245,
    completedBookings: 230,
    cancelledBookings: 8,
    earnings: 185000,
    pendingPayouts: 12500,
    onTimePercentage: 94,
    acceptanceRate: 96,
    documents: [
      {
        id: "d1",
        type: "aadhar",
        name: "Aadhar Card",
        status: "verified",
        uploadDate: "2023-06-15",
        verifiedDate: "2023-06-16",
      },
      {
        id: "d2",
        type: "pan",
        name: "PAN Card",
        status: "verified",
        uploadDate: "2023-06-15",
        verifiedDate: "2023-06-16",
      },
    ],
    subscription: {
      plan: "premium",
      startDate: "2023-06-20",
      endDate: "2024-06-20",
      slots: 50,
      usedSlots: 42,
      monthlyFee: 2500,
      status: "active",
    },
    compliance: {
      backgroundCheck: "completed",
      trainingCompleted: true,
      insuranceValid: true,
      licenseValid: true,
      lastAuditDate: "2024-01-15",
      complianceScore: 95,
    },
  },
  {
    id: "p2",
    name: "PestAway Solutions",
    email: "info@pestaway.com",
    phone: "+91 87654 32109",
    city: "Delhi",
    areas: ["CP", "Karol Bagh", "Lajpat Nagar"],
    services: ["Pest Control", "Termite Treatment", "Rodent Control"],
    joinDate: "2023-08-20",
    status: "active",
    kycStatus: "verified",
    rating: 4.6,
    totalBookings: 189,
    completedBookings: 175,
    cancelledBookings: 12,
    earnings: 142000,
    pendingPayouts: 8900,
    onTimePercentage: 89,
    acceptanceRate: 92,
    documents: [
      {
        id: "d3",
        type: "license",
        name: "Pest Control License",
        status: "verified",
        uploadDate: "2023-08-20",
        verifiedDate: "2023-08-22",
      },
    ],
    subscription: {
      plan: "basic",
      startDate: "2023-08-25",
      endDate: "2024-08-25",
      slots: 25,
      usedSlots: 18,
      monthlyFee: 1500,
      status: "active",
    },
    compliance: {
      backgroundCheck: "completed",
      trainingCompleted: true,
      insuranceValid: true,
      licenseValid: true,
      lastAuditDate: "2024-02-10",
      complianceScore: 88,
    },
  },
  {
    id: "p3",
    name: "CoolTech Repairs",
    email: "support@cooltech.com",
    phone: "+91 76543 21098",
    city: "Bangalore",
    areas: ["Koramangala", "Indiranagar", "Whitefield"],
    services: ["AC Repair", "AC Installation", "AC Maintenance"],
    joinDate: "2024-01-10",
    status: "pending",
    kycStatus: "pending",
    rating: 0,
    totalBookings: 0,
    completedBookings: 0,
    cancelledBookings: 0,
    earnings: 0,
    pendingPayouts: 0,
    onTimePercentage: 0,
    acceptanceRate: 0,
    documents: [
      {
        id: "d4",
        type: "aadhar",
        name: "Aadhar Card",
        status: "pending",
        uploadDate: "2024-01-10",
      },
      {
        id: "d5",
        type: "license",
        name: "Electrical License",
        status: "rejected",
        uploadDate: "2024-01-10",
        rejectionReason: "Document not clear, please reupload",
      },
    ],
    subscription: {
      plan: "basic",
      startDate: "2024-01-15",
      endDate: "2024-01-15",
      slots: 0,
      usedSlots: 0,
      monthlyFee: 0,
      status: "suspended",
    },
    compliance: {
      backgroundCheck: "pending",
      trainingCompleted: false,
      insuranceValid: false,
      licenseValid: false,
      complianceScore: 25,
    },
  },
]

export const mockPartnerPayouts: PartnerPayout[] = [
  {
    id: "po1",
    partnerId: "p1",
    amount: 12500,
    period: "2024-02",
    status: "pending",
    requestDate: "2024-02-28",
  },
  {
    id: "po2",
    partnerId: "p1",
    amount: 15200,
    period: "2024-01",
    status: "completed",
    requestDate: "2024-01-31",
    processedDate: "2024-02-02",
    razorpayOrderId: "order_123456",
  },
  {
    id: "po3",
    partnerId: "p2",
    amount: 8900,
    period: "2024-02",
    status: "processing",
    requestDate: "2024-02-28",
  },
]

export const mockPartnerPerformance: PartnerPerformance[] = [
  {
    partnerId: "p1",
    period: "2024-02",
    bookings: 28,
    revenue: 21500,
    rating: 4.8,
    onTimeDelivery: 96,
    customerSatisfaction: 94,
    repeatCustomers: 18,
  },
  {
    partnerId: "p2",
    period: "2024-02",
    bookings: 22,
    revenue: 16800,
    rating: 4.6,
    onTimeDelivery: 91,
    customerSatisfaction: 89,
    repeatCustomers: 12,
  },
]
