import type { SupportTicket, Review } from "@/types/support"

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "1",
    customerId: "cust_1",
    customerName: "Priya Sharma",
    bookingId: "book_123",
    type: "complaint",
    priority: "high",
    status: "open",
    subject: "Service quality issue",
    description: "The cleaning service was not up to the expected standard. Several areas were missed.",
    assignedTo: "support_agent_1",
    createdAt: "2024-03-15T10:30:00Z",
    updatedAt: "2024-03-15T10:30:00Z",
  },
  {
    id: "2",
    customerId: "cust_2",
    customerName: "Rahul Kumar",
    type: "query",
    priority: "medium",
    status: "in_progress",
    subject: "Service availability inquiry",
    description: "I want to know if AC repair service is available in my area (Sector 15, Noida).",
    assignedTo: "support_agent_2",
    createdAt: "2024-03-14T15:45:00Z",
    updatedAt: "2024-03-15T09:20:00Z",
  },
  {
    id: "3",
    customerId: "cust_3",
    customerName: "Anjali Patel",
    bookingId: "book_456",
    type: "refund",
    priority: "urgent",
    status: "resolved",
    subject: "Refund request for cancelled service",
    description: "Partner cancelled the service at the last minute. Requesting full refund.",
    assignedTo: "support_agent_1",
    createdAt: "2024-03-13T12:00:00Z",
    updatedAt: "2024-03-14T16:30:00Z",
    resolvedAt: "2024-03-14T16:30:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    customerId: "cust_1",
    customerName: "Priya Sharma",
    partnerId: "partner_1",
    partnerName: "CleanPro Services",
    bookingId: "book_123",
    serviceId: "service_1",
    serviceName: "Deep House Cleaning",
    rating: 2,
    comment: "Service was below expectations. Several areas were not cleaned properly.",
    isPublic: true,
    createdAt: "2024-03-15T11:00:00Z",
  },
  {
    id: "2",
    customerId: "cust_4",
    customerName: "Vikram Singh",
    partnerId: "partner_2",
    partnerName: "Beauty at Home",
    bookingId: "book_789",
    serviceId: "service_2",
    serviceName: "Hair Styling",
    rating: 5,
    comment: "Excellent service! Very professional and skilled stylist.",
    isPublic: true,
    createdAt: "2024-03-14T18:30:00Z",
  },
]
